name: Monthly Patch Cover

on:
  schedule:
    - cron: "0 4 15 * *" # Runs at 4:00 AM on the 15th of every month
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests 

      - name: Run script
        run: python DanceCubeCover/getOfficialCover.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Update Monthly Patch Cover"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add DanceCubeCover/CoverData.json
          git commit -m "${COMMIT_MESSAGE}" || echo "No changes to commit"  
          git push
          
