name: Monthly Patch Cover

on:
  schedule:
    - cron: "0 4 15 * *" # Runs at 4:00 AM on the 15th of every month
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests 

      - name: Run script
        run: python DanceCubeCover/getOfficialCover.py

      - name: Commit and Push
  # You may pin to the exact commit or the version.
  # uses: flex-development/gh-commit@177be4b5bca1b102400ca7220932d9ff7980fddb
        uses: flex-development/gh-commit@1.0.0
        with:
          files: # optional
    # Commit message
          message: Cover Update

